### ISSUE TITLE
Question - need more info from CLI

### ISSUE THREAD

**Issue by darrens280** [f2calv/yamlizr#105]
Hi. I was excited to find this tool, and would like to try it out, to convert Classic Release pipelines into YML-based pipeline. 

I have downloaded .Net pre-req, and created an Azure PAT token as specified, but when I run the CLI, I get confirmation that it has connected to my Azure org and project, but then it just sits, and does nothing (as per screenshot below). I can confirm the target output folder exists. I have also tried to filter against one specific release pipeline, but still I get no output after the connection is made...

1- Is there any way to get some more verbose logging about what it is doing, or if it has perhaps errored in the background?
2- Does the --filter require a release pipeline 'Name' or 'ID' as the value?

![image](https://user-images.githubusercontent.com/39370017/126147650-74e223d7-72e8-4032-8747-ae9d8a7e7239.png)

Thank you

**Comment by f2calv** [comment]
Can you provide the full command line you are using? (obsfucated in key areas of course!)

**Comment by darrens280** [comment]
yamlizr generate -pat "xxxxxxxxxxxxxxxx" -org "xxxxxxxx" -proj "xxxxxxxxxxx" -out "c:/temp/myoutputfolder" --filter "my-azure-report"

Tried single quotes, and double quotes
Tried fwd slashes, and back slashes for the output path
Same result

System:
- Windows 10 (1903)
- .NET 5.0 SDK (v5.0.302) - Windows x64 installed
- PowerShell 5.1
- running from PowerShell ISE x64 (as Admin)

NOW RESOLVED:
I tried it using the normal PowerShell console (As admin), and all worked as expected, and the ouput .yml files were generated straight away.

Thanks
