### ISSUE TITLE
Support for reusable workflows

### ISSUE THREAD

**Issue by devkeydet** [f2calv/yamlizr#114]
GitHub has introduced reusable workflows in beta:
https://docs.github.com/en/actions/learn-github-actions/reusing-workflows

Please consider converting Azure DevOps templates to reusable workflows.

**Comment by f2calv** [comment]
Thanks for the info.

However this app is primarily concerned with classic azdo pipelines to YAML, and the GitHub Actions part of the app is entirely handled by [AzurePipelinesToGitHubActionsConverter](https://github.com/samsmithnz/AzurePipelinesToGitHubActionsConverter) by @samsmithnz so I would advise taking your suggestion [there](https://github.com/samsmithnz/AzurePipelinesToGitHubActionsConverter/issues).
