### ISSUE TITLE
Organiztion path not started with https://dev.azure.com

### ISSUE THREAD

**Issue by apgaurav-p-singh** [f2calv/yamlizr#160]
Organiztion parh not started with https://dev.azure.com , it is on premises but command parameter org
{{yamlizr generate -pat trnxk6st4jomz7eweka **-org** https://ts.xm.com/tfs/APPS1 -proj APPL_CSD_BOX_STSI_CODE -out C:/Users}}
is searching with 
https://dev.azure.com + Org name

**Comment by KenzoB73** [comment]
Having the same issue with on-premises.  Any solution yet?

**Comment by f2calv** [comment]
@apgaurav-p-singh @KenzoB73 this issue has been addressed as part of the v2.0 release.
FWIW it would have taken ~10 minutes to fix this yourself and raise a PR, this the world of open-source you know...
